#!/bin/bash
THIS_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit
source ./scripts/default_env

"${IOCMAN_PY_BIN}"/pyuic5 -o iocmanager/ioc_ui.py ui/ioc.ui
"${IOCMAN_PY_BIN}"/pyuic5 -o iocmanager/hostname_ui.py ui/hostname.ui
"${IOCMAN_PY_BIN}"/pyuic5 -o iocmanager/auth_ui.py ui/auth.ui
"${IOCMAN_PY_BIN}"/pyuic5 -o iocmanager/details_ui.py ui/details.ui
"${IOCMAN_PY_BIN}"/pyuic5 -o iocmanager/commit_ui.py ui/commit.ui
