#!/bin/bash
export PSPKG_RELEASE=controls-0.1.9
source $PSPKG_ROOT/etc/set_env.sh
pyuic5 -o ioc_ui.py ioc.ui
pyuic5 -o hostname_ui.py hostname.ui
pyuic5 -o auth_ui.py auth.ui
pyuic5 -o details_ui.py details.ui
pyuic5 -o commit_ui.py commit.ui
