#!/bin/sh
# Usage: fixTelnet port
if [ -x /etc/pathinit ]; then
    source /etc/pathinit
else
    export PSPKG_ROOT=/reg/common/package
    export PYPS_ROOT=/cds/group/pcds/pyps
    export IOC_ROOT=/cds/group/pcds/package/epics/3.14/ioc
    export CAMRECORD_ROOT=/cds/group/pcds/controls/camrecord
    export IOC_DATA=/cds/data/iocData
    export IOC_COMMON=/cds/data/iocCommon
fi

host=`hostname -s`
cfg=`awk /$host/'{print $2;}'  $PYPS_ROOT/config/hosts.special`
if [ "${cfg}X" == "X" ]; then
    cfg=`echo $host | awk '{print substr($0,5,3);}' -`
fi
export PSPKG_RELEASE=controls-basic-0.0.1
source $PSPKG_ROOT/etc/set_env.sh
if [ X$SCRIPTROOT == X ]; then
    export SCRIPTROOT=$PYPS_ROOT/config/$cfg/iocmanager
fi
python $SCRIPTROOT/fixTelnet.py "$@"
