#!/bin/bash
# Usage: getDirectory IOC HUTCH

export PSPKG_ROOT=/reg/common/package
export PSPKG_RELEASE=controls-basic-0.0.1
source $PSPKG_ROOT/etc/set_env.sh
if [ X$SCRIPTROOT == X ]; then
    export SCRIPTROOT=/reg/g/pcds/pyps/apps/ioc/$2
fi
$SCRIPTROOT/getDirectory.py "$@"
