#!/bin/sh

# Find our standard configuration.
host=`hostname -s`
cfg=`awk /$host/'{print $2;}'  $PYPS_ROOT/config/hosts.special`
if [ "${cfg}X" == "X" ]; then
    cfg=`echo $host | awk '{print substr($0,5,3);}' -`
fi
echo Using configuration $cfg.

export SCRIPTROOT=$PYPS_ROOT/config/$cfg/iocmanager

# Setup our path, so we can find procServ/procmgrd!
export PSPKG_RELEASE=controls-basic-0.0.3
source $PSPKG_ROOT/etc/set_env.sh
export PATH=${SCRIPTROOT}:$PATH

source $SCRIPTROOT/initIOC.hutch
