# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ioc.ui'
#
# Created: Mon Jul 10 12:42:34 2017
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(713, 525)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout.addWidget(self.tableView)
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout = QtGui.QGridLayout(self.widget_2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.IOCname = QtGui.QLineEdit(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.IOCname.sizePolicy().hasHeightForWidth())
        self.IOCname.setSizePolicy(sizePolicy)
        self.IOCname.setMinimumSize(QtCore.QSize(170, 0))
        self.IOCname.setReadOnly(True)
        self.IOCname.setObjectName(_fromUtf8("IOCname"))
        self.gridLayout.addWidget(self.IOCname, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.heartbeat = QtGui.QLineEdit(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.heartbeat.sizePolicy().hasHeightForWidth())
        self.heartbeat.setSizePolicy(sizePolicy)
        self.heartbeat.setMinimumSize(QtCore.QSize(170, 0))
        self.heartbeat.setReadOnly(True)
        self.heartbeat.setObjectName(_fromUtf8("heartbeat"))
        self.gridLayout.addWidget(self.heartbeat, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.tod = QtGui.QLineEdit(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.tod.sizePolicy().hasHeightForWidth())
        self.tod.setSizePolicy(sizePolicy)
        self.tod.setMinimumSize(QtCore.QSize(170, 0))
        self.tod.setReadOnly(True)
        self.tod.setObjectName(_fromUtf8("tod"))
        self.gridLayout.addWidget(self.tod, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.boottime = QtGui.QLineEdit(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.boottime.sizePolicy().hasHeightForWidth())
        self.boottime.setSizePolicy(sizePolicy)
        self.boottime.setMinimumSize(QtCore.QSize(170, 0))
        self.boottime.setReadOnly(True)
        self.boottime.setObjectName(_fromUtf8("boottime"))
        self.gridLayout.addWidget(self.boottime, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.location = QtGui.QLineEdit(self.widget_2)
        self.location.setReadOnly(True)
        self.location.setObjectName(_fromUtf8("location"))
        self.gridLayout.addWidget(self.location, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.description = QtGui.QLineEdit(self.widget_2)
        self.description.setReadOnly(True)
        self.description.setObjectName(_fromUtf8("description"))
        self.gridLayout.addWidget(self.description, 2, 3, 1, 1)
        self.userLabel = QtGui.QLabel(self.widget_2)
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.gridLayout.addWidget(self.userLabel, 2, 4, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        self.menuConfiguration.setObjectName(_fromUtf8("menuConfiguration"))
        self.menuIOC_Control = QtGui.QMenu(self.menubar)
        self.menuIOC_Control.setObjectName(_fromUtf8("menuIOC_Control"))
        self.menuMisc = QtGui.QMenu(self.menubar)
        self.menuMisc.setObjectName(_fromUtf8("menuMisc"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionApply = QtGui.QAction(MainWindow)
        self.actionApply.setObjectName(_fromUtf8("actionApply"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionRevert = QtGui.QAction(MainWindow)
        self.actionRevert.setObjectName(_fromUtf8("actionRevert"))
        self.actionReboot = QtGui.QAction(MainWindow)
        self.actionReboot.setObjectName(_fromUtf8("actionReboot"))
        self.actionLog = QtGui.QAction(MainWindow)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionConsole = QtGui.QAction(MainWindow)
        self.actionConsole.setObjectName(_fromUtf8("actionConsole"))
        self.actionRemember = QtGui.QAction(MainWindow)
        self.actionRemember.setObjectName(_fromUtf8("actionRemember"))
        self.actionAuth = QtGui.QAction(MainWindow)
        self.actionAuth.setObjectName(_fromUtf8("actionAuth"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionHard_Reboot = QtGui.QAction(MainWindow)
        self.actionHard_Reboot.setObjectName(_fromUtf8("actionHard_Reboot"))
        self.actionReboot_Server = QtGui.QAction(MainWindow)
        self.actionReboot_Server.setObjectName(_fromUtf8("actionReboot_Server"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.menuConfiguration.addAction(self.actionApply)
        self.menuConfiguration.addAction(self.actionSave)
        self.menuConfiguration.addAction(self.actionRevert)
        self.menuIOC_Control.addAction(self.actionReboot)
        self.menuIOC_Control.addAction(self.actionHard_Reboot)
        self.menuIOC_Control.addAction(self.actionReboot_Server)
        self.menuIOC_Control.addAction(self.actionLog)
        self.menuIOC_Control.addAction(self.actionConsole)
        self.menuMisc.addAction(self.actionHelp)
        self.menuMisc.addAction(self.actionRemember)
        self.menuMisc.addAction(self.actionAuth)
        self.menuMisc.addAction(self.actionQuit)
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuIOC_Control.menuAction())
        self.menubar.addAction(self.menuMisc.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Current IOC:", None))
        self.label_3.setText(_translate("MainWindow", "Heartbeat:", None))
        self.label_2.setText(_translate("MainWindow", "Time of Day:", None))
        self.label_4.setText(_translate("MainWindow", "Boot Time:", None))
        self.label_5.setText(_translate("MainWindow", "Location:", None))
        self.label_6.setText(_translate("MainWindow", "Description:", None))
        self.userLabel.setText(_translate("MainWindow", "User: Guest", None))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Configuration", None))
        self.menuIOC_Control.setTitle(_translate("MainWindow", "IOC Control", None))
        self.menuMisc.setTitle(_translate("MainWindow", "Utilities", None))
        self.actionApply.setText(_translate("MainWindow", "Apply", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionRevert.setText(_translate("MainWindow", "Revert", None))
        self.actionReboot.setText(_translate("MainWindow", "Soft IOC Reboot", None))
        self.actionLog.setText(_translate("MainWindow", "Show Log", None))
        self.actionConsole.setText(_translate("MainWindow", "Show Console", None))
        self.actionRemember.setText(_translate("MainWindow", "Remember Versions", None))
        self.actionAuth.setText(_translate("MainWindow", "Authenticate User", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionHard_Reboot.setText(_translate("MainWindow", "Hard IOC Reboot", None))
        self.actionReboot_Server.setText(_translate("MainWindow", "Reboot Server", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))

