#!/bin/sh
# Usage: startAll HUTCH HOSTNAME
if [ -x /etc/pathinit ]; then
    source /etc/pathinit
else
    export PSPKG_ROOT=/reg/common/package
    export PYPS_ROOT=/cds/group/pcds/pyps
    export IOC_ROOT=/cds/group/pcds/package/epics/3.14/ioc
    export CAMRECORD_ROOT=/cds/group/pcds/controls/camrecord
    export IOC_DATA=/cds/data/iocData
    export IOC_COMMON=/cds/data/iocCommon
fi

export PSPKG_RELEASE=controls-basic-0.0.1
source $PSPKG_ROOT/etc/set_env.sh
if [ X$SCRIPTROOT == X ]; then
    export SCRIPTROOT=/cds/group/pcds/pyps/config/$1/iocmanager
fi
python $SCRIPTROOT/startAll.py "$@"
