#!/bin/sh
# Usage: startAll HUTCH HOSTNAME
if [ -x /etc/pathinit ]; then
    source /etc/pathinit
else
    export PSPKG_ROOT=/reg/common/package
    export PYPS_ROOT=/reg/g/pcds/pyps
    export IOC_ROOT=/reg/g/pcds/package/epics/3.14/ioc
    export CAMRECORD_ROOT=/reg/g/pcds/controls/camrecord
    export IOC_DATA=/reg/d/iocData
    export IOC_COMMON=/reg/d/iocCommon
fi

export PSPKG_RELEASE=controls-basic-0.0.3
source $PSPKG_ROOT/etc/set_env.sh
if [ X$SCRIPTROOT == X ]; then
    export SCRIPTROOT=/reg/g/pcds/pyps/config/$1/iocmanager
fi
python $SCRIPTROOT/startAll.py "$@"
