#!/bin/csh
# Usage: startProc IOCNAME PORT HUTCH

if ($?SCRIPTROOT == 0) setenv SCRIPTROOT /reg/g/pcds/pyps/apps/ioc/latest
set ioc = $1
set port = $2
set cfg = $3
shift;shift;shift
set dir = `$SCRIPTROOT/getDirectory $ioc $cfg`
cd /reg/g/pcds/package/epics/3.14
if (-d $dir) cd $dir
if (-f env.csh) source env.csh
if (-d children/build/iocBoot/$ioc) cd children/build/iocBoot/$ioc
if (-d build/iocBoot/$ioc) cd build/iocBoot/$ioc
if (-d iocBoot/$ioc) cd iocBoot/$ioc
if (-f env.csh) source env.csh
echo $$ `hostname -s` $port $dir >/reg/g/pcds/pyps/config/.status/$cfg/$ioc
chmod g+w /reg/g/pcds/pyps/config/.status/$cfg/$ioc
if (-f ../../archive/$ioc.archive) then
    cp -f -p ../../archive/$ioc.archive /reg/d/iocData/$ioc/archive
endif
set cmd = $1
shift
exec $cmd $argv
