#!/bin/bash
mydir=`dirname $0`
if [ $# -eq 0 ];
    then
    echo Usage: find_pv pv_name [pv_name2 ...]
    echo This script will search for each specified EPICS PV in:
    echo "  /reg/d/iocData/ioc*/iocInfo/IOC.pvlist"
    echo ""
    echo Then it looks for the linux host or hard IOC hostname in:
    echo "  /reg/d/iocCommon/hosts/ioc*/startup.cmd"
    echo "  /reg/d/iocCommon/hioc/ioc*/startup.cmd"
    echo "If no host is found, the IOC will not autoboot after a power cycle!"
    echo ""
    echo Finally it looks for the boot directory in:
    echo "  /reg/d/iocCommon/{hioc,sioc}/<ioc-name>/startup.cmd"
    echo ""
    echo "Hard IOC boot directories are shown with the nfs mount name."
    echo "Typically this is /iocs mounting /reg/g/pcds/package/epics/ioc"
    exit 1;
fi 
for pv in $@;
  do
  echo PV: $pv
  ioc_list=`/bin/egrep -l -e "$pv" /reg/d/iocData/ioc*/iocInfo/IOC.pvlist | /bin/cut -d / -f5`
  for ioc in $ioc_list;
    do
    echo "  IOC: $ioc"

			# Look for IOC PV root
    ioc_pv=`/bin/egrep UPTIME /reg/d/iocData/$ioc/iocInfo/IOC.pvlist | /bin/sed -e "s/:UPTIME.*//"`
    if (( ${#ioc_pv} == 0 ));
	then
	echo "  IOC_PV: Not found!"
    else
	echo "  IOC_PV: $ioc_pv"
    fi

			# Look for linux hosts
    host_list=`/bin/egrep -l -e "$ioc" /reg/d/iocCommon/hosts/ioc*/startup.cmd | /bin/cut -d / -f6`
    for h in $host_list;
      do
      echo "  HOST: $h"
    done

    if [ -f /reg/d/iocCommon/sioc/$ioc/startup.cmd ];
	then
				# Look for soft IOC boot directories
	boot_list=`/bin/egrep -w -e "^cd" /reg/d/iocCommon/sioc/$ioc/startup.cmd | /bin/awk '{ print $2}'`
	if (( ${#boot_list} ));
	    then
	    echo "  STARTUP: /reg/d/iocCommon/sioc/$ioc/startup.cmd"
	    for d in $boot_list;
	      do
	      echo "  BOOT_DIR: $d"
	    done
	fi
    fi

			# Look for hard ioc
    hioc_list=`/bin/egrep -l -e "$ioc" /reg/d/iocCommon/hioc/ioc*/startup.cmd | /bin/cut -d / -f6`
    if (( ${#hioc_list} ));
	then
	for hioc in $hioc_list;
	  do
	  echo "  HIOC: $hioc"
	  echo "  STARTUP: /reg/d/iocCommon/hioc/$hioc/startup.cmd"
	  boot_list=`/bin/egrep -w -e "^chdir" /reg/d/iocCommon/hioc/$hioc/startup.cmd | /bin/cut -d \" -f2`
	  for d in $boot_list;
	    do
	    echo "  BOOT_DIR: $d"
	  done
	done
    fi

    if (( ${#host_list} == 0 && ${#hioc_list} == 0 ));
	then
	echo "  HOST: Not found!"
	echo "  HIOC: Not found!"
    fi

			# Show boot directory for this PV
    if (( ${#boot_list} == 0 ));
	then
	echo "  BOOT_DIR: Not found!"
    fi

                        # Look for IocManager Configs
    echo "  IocManager Configs:"
    $mydir/find_ioc --name $ioc
    

  done
done
