#!/bin/bash
# Usage: startProc IOCNAME PORT HUTCH

ioc=$1
port=$2
cfg=$3
shift;shift;shift
if test X$SCRIPTROOT == X; then export SCRIPTROOT=/reg/g/pcds/pyps/apps/ioc/$cfg; fi

# Setup the IOC user environment.
export IOC=$ioc
source /reg/d/iocCommon/All/${cfg}_env.sh

dir=`$SCRIPTROOT/getDirectory $ioc $cfg`
cd /reg/g/pcds/package/epics/3.14
if test -d $dir; then cd $dir; fi
if test -f env.sh; then source env.sh; fi
if test -d children/build/iocBoot/$ioc; then cd children/build/iocBoot/$ioc; fi
if test -d build/iocBoot/$ioc; then cd build/iocBoot/$ioc; fi
if test -d iocBoot/$ioc; then cd iocBoot/$ioc; fi
if test -f env.sh; then source env.sh; fi
echo $$ `hostname -s` $port $dir >/reg/g/pcds/pyps/config/.status/$cfg/$ioc
chmod g+w /reg/g/pcds/pyps/config/.status/$cfg/$ioc
if test -f ../../archive/$ioc.archive; then
    cp -f -p ../../archive/$ioc.archive /reg/d/iocData/$ioc/archive;
fi
cmd=$1
shift
exec $cmd $@
