#!/usr/bin/bash
# Usage: fixTelnet port
THIS_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}/.." || exit
source "${THIS_DIR}"/default_env

"${IOCMAN_PY_BIN}"/python -m iocmanager.scripts.fix_telnet "$@"
