#!/usr/bin/bash
# Usage: getDirectory IOC HUTCH
THIS_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}/.." || exit
source "${THIS_DIR}"/default_env

"${IOCMAN_PY_BIN}"/python iocmanager.scripts.get_directory "$@"
