#!/usr/bin/bash

THIS_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}/.." || exit
source "${THIS_DIR}"/default_env

# Setup our path, so we can find procServ/procmgrd and scripts from iocmanager
export PATH="${SCRIPTROOT}:${PACKAGE_SITE_TOP}/procServ-2.8.0/${T_A}/bin:${PATH}"

source "${SCRIPTROOT}"/initIOC.hutch
